<a href="https://colab.research.google.com/github/ZuorthOG/Midterm-Dataset/blob/main/Midterm_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Clifford Amoah MAT 301

## Dataset Description

### College Basketball Dataset

This dataset contains statistics from NCAA Division I college basketball teams across multiple seasons. Overall, the dataset is used to analyze team performance, statistics, and trends in Division I college basketball over multiple seasons.

### Key Features
- **Season Information**: Identifies the year/season each team’s data comes from (2013–2019, 2021–2024, and 2025 updates).

- **Team Name**: The Division I college basketball team the statistics belong to.

- **Conference**: The conference each team competes in

- **Wins and Losses**: Total number of games won and lost during the season.

- **Offensive Statistics** : Metrics that measure how effective a team is at scoring, such as offensive efficiency and shooting percentages.

- **Defensive Statistics** : Measures of how well a team prevents opponents from scoring, including defensive efficiency.

- **Advanced Metrics**: Analytics such as effective field goal percentage, turnover rates, rebound rates, and strength of schedule.

- **Postseason Indicators**: Some seasons include information about tournament appearances or rankings.

### Column Descriptions
- **`RK`**: Name of the Division I college basketball team.

- **`CONF`**: The athletic conference the team belongs to.

- **`G`**: Total number of games played in the season.

- **`W`**: Total number of games won.

- **`ADJOE`**: Adjusted Offensive Efficiency

- **`ADJDE`**: Adjusted Defensive Efficiency

- **`BARTHAG`**: Power rating representing the probability of beating an average Division I team.

- **`EFG_O`**: Effective field goal percentage for the team’s offense.

- **`EFG_D`**: Effective field goal percentage allowed by the team’s defense.

- **`TOR`**: Turnover percentage allowed (turnover rate).

- **`TORD`**: Turnover percentage committed (steal rate by opponents).

- **`ORB`**: Offensive rebound rate.

- **`DRB`**: Offensive rebound rate allowed (defensive rebounding ability of opponents).

- **`FTR`**: Free throw rate (how often the team gets to the free throw line).

- **`FTRD`**: Free throw rate allowed.

- **`2P_O`**: Two-point shooting percentage.

- **`2P_D`**: Two-point shooting percentage allowed.

- **`3P_O`**: Three-point shooting percentage.

- **`3P_D`**: Three-point shooting percentage allowed.

- **`ADJ_T`**: Adjusted tempo (estimated possessions per 40 minutes against an average tempo team).

- **`WAB`**: Wins Above Bubble (how a team performs relative to the NCAA tournament cutoff).

- **`POSTSEASON`**: The round where the team was eliminated in the NCAA tournament (e.g., R64, S16, F4, Champion).

- **`SEED`**: Tournament seed assigned to the team.

- **`YEAR`**: The season year.

**Source**: [Kaggle Datasets](https://www.kaggle.com/datasets/andrewsundberg/college-basketball-dataset)

## Data Cleaning and Wranling

I'm going to load my data and preview a couple of rows

In [2]:
#libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# Loading out dataset
basketball_data = pd.read_csv('https://raw.githubusercontent.com/ZuorthOG/Midterm-Dataset/refs/heads/main/cbb.csv')
basketball_data.shape

(3885, 24)

In [6]:
basketball_data.head()

,TEAM,CONF,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,...,FTRD,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,POSTSEASON,SEED,YEAR
0,North Carolina,ACC,40,33,123.3,94.9,0.9531,52.6,48.1,15.4,...,30.4,53.9,44.6,32.7,36.2,71.7,8.6,2ND,1.0,2016
1,Wisconsin,B10,40,36,129.1,93.6,0.9758,54.8,47.7,12.4,...,22.4,54.8,44.7,36.5,37.5,59.3,11.3,2ND,1.0,2015
2,Michigan,B10,40,33,114.4,90.4,0.9375,53.9,47.7,14.0,...,30.0,54.7,46.8,35.2,33.2,65.9,6.9,2ND,3.0,2018
3,Texas Tech,B12,38,31,115.2,85.2,0.9696,53.5,43.0,17.7,...,36.6,52.8,41.9,36.5,29.7,67.5,7.0,2ND,3.0,2019
4,Gonzaga,WCC,39,37,117.8,86.3,0.9728,56.6,41.1,16.2,...,26.9,56.3,40.0,38.2,29.0,71.5,7.7,2ND,1.0,2017

There's a couple of missing values, I will display this in the following.

In [12]:
basketball_data.isnull().sum()

TEAM          0
CONF          0
G             0
W             0
ADJOE         0
ADJDE         0
BARTHAG       0
EFG_O         0
EFG_D         0
TOR           0
TORD          0
ORB           0
DRB           0
FTR           0
FTRD          0
2P_O          0
2P_D          0
3P_O          0
3P_D          0
ADJ_T         0
WAB           0
POSTSEASON    0
SEED          0
YEAR          0
dtype: int64

I decided to fill in the data for post season and seed.

In [11]:
basketball_data['SEED'] = basketball_data['SEED'].fillna(0)
basketball_data['POSTSEASON'] = basketball_data['POSTSEASON'].fillna('No Tournament')

I'm going to check for duplicates

In [13]:
basketball_data.duplicated().sum()

np.int64(0)